# Generated by Django 5.2.4 on 2025-07-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeptalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='deeptalk.schedule'),
        ),
    ]
